[package]
name = "webb-cli"
version = "0.1.0"
authors = [
   "Webb Developers <drew@webb.tools>",
   "Shady Khalifa <shekohex@gmail.com>"
]
edition = "2018"


[[bin]]
name = "webb"
path = "src/main.rs"
required-features = ["cli"]

[dependencies]
async-std = "1.8"
async-trait = "0.1"
log = "0.4"
substrate-subxt = "0.14"
thiserror = "1.0"
zeroize = "^1"
tiny-bip39 = "0.8"

# CLI
anyhow = { version = "1.0", optional = true }
env_logger = { version = "0.8", optional = true }
clap = { version = "3.0.0-beta.2", optional = true }
keyring = { version = "0.10", optional = true }

[features]
default = []
cli = ["clap", "env_logger", "anyhow"]

