[package]
name = "webb-cli"
version = "0.1.0"
authors = [
   "Webb Developers <drew@webb.tools>",
   "Shady Khalifa <shekohex@gmail.com>"
]
edition = "2018"


[[bin]]
name = "webb"
path = "src/main.rs"
required-features = ["cli"]

[dependencies]
async-std = "1.8"
async-trait = "0.1"
log = "0.4"
subxt = { version = "0.14", package = "substrate-subxt" }
thiserror = "1.0"
zeroize = "^1"
tiny-bip39 = "0.8"
uuid = { version = "0.8", features = ["v4"] }
codec = { package = "parity-scale-codec", version = "1.3.6", features = ["derive", "full"] }

# Pallets
frame-support = "2.0.1"

# CLI
anyhow = { version = "1.0", optional = true }
env_logger = { version = "0.8", optional = true }
structopt = { version = "0.3", optional = true, features = ["paw"] }
paw = { version = "1.0", optional = true }
sled = { version = "0.34", optional = true }
directories-next = { version = "2.0", optional = true }
prost = { version = "0.7", optional = true }
rpassword = { version = "5.0", optional = true }
secrecy = { version = "0.7", optional = true }

[features]
default = []
cli = [
   "structopt",
   "paw",
   "env_logger",
   "anyhow",
   "async-std/attributes",
   "sled",
   "directories-next",
   "prost",
   "rpassword",
   "secrecy",
]
integration-tests = []

[dev-dependencies]
async-std = { version = "1.8", features = ["attributes"] }
sp-keyring = "2.0.1"

